# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.synced_folder "../../salt/", "/srv/salt", type: "rsync"

  config.vm.provision "shell", path: "../../files/sh/salt.sh"
end
